import{S as h,A as w}from"./assets/vendor-B_FypTfd.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();const y=1440;let f=null,p=null;function v(){if(f)return;const n=document.querySelector(".how-swiper");n&&(f=new h(n,{modules:[w],slidesPerView:1.2,spaceBetween:16,loop:!0,speed:800,autoplay:{delay:3e3,disableOnInteraction:!1,pauseOnMouseEnter:!0}}))}function L(){if(p)return;const n=document.querySelector(".characters-swiper");n&&(p=new h(n,{modules:[w],slidesPerView:1.2,spaceBetween:16,loop:!0,speed:800,autoplay:{delay:3e3,disableOnInteraction:!1,pauseOnMouseEnter:!0}}))}function S(){f&&(f.destroy(!0,!0),f=null)}function E(){p&&(p.destroy(!0,!0),p=null)}function g(){if(window.innerWidth>=y){S(),E();return}v(),L()}g();window.addEventListener("resize",g);document.querySelectorAll(".faq-acc-el-trigger").forEach(n=>{n.addEventListener("click",()=>{const r=n.closest(".faq-acc-el"),l=r.querySelector(".faq-acc-el-descr-frame");r.classList.contains("open")?(r.classList.remove("open"),l.style.maxHeight="0"):(r.classList.add("open"),l.style.maxHeight=l.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),r=n.querySelector(".icon"),l=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 8H17M6 16H17M6 12H17" stroke="#353334" stroke-linecap="square" />
</svg>
    `,o=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 8L12 12M12 12L8 16M12 12L16 16M12 12L16 8" stroke="#353334" stroke-linecap="square" stroke-linejoin="round" />
</svg>
    `;n.addEventListener("click",()=>{t=!t,r.innerHTML=t?o:a,t?s():i()}),d.forEach(u=>u.addEventListener("click",()=>{i(),r.innerHTML=a,t=!1})),window.addEventListener("scroll",c);function s(){l.style.display="block"}function i(){l.style.display="none"}function c(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function n(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function r(o){const s=document.getElementById(o);if(!s)return;const i=n(),c=s.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:c,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(s){const i=this.getAttribute("href");if(!i)return;const[c,u]=i.split("#");if(!u)return;const m=window.location.pathname.split("/").pop();!(c===""||c==="./"||c===m||c==="./"+m)||!document.getElementById(u)||(s.preventDefault(),r(u),t(u))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(i=>i.classList.remove("active"));const s=document.querySelector(`.navigation-item a[href*="#${o}"]`);s&&s.closest(".navigation-item").classList.add("active")}function a(){const o=window.pageYOffset+n()+100;d.forEach(s=>{const i=s.offsetTop,c=i+s.offsetHeight;o>=i&&o<c&&t(s.id)})}if(window.addEventListener("scroll",a),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{r(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
